[project]
name = "quest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "fire>=0.6.0",
    "jupyter>=1.1.1",
    "nanoid>=2.0.0",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
]

[project.scripts]
character = "quest1.delivery.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
